export var UPDATE_LOCATION = "UPDATE_LOCATION";
export var UPDATE_REQUEST = "UPDATE_REQUEST";
export var UPDATE_CONTENT = "UPDATE_CONTENT";
export var UPDATE_METADATA = "UPDATE_METADATA";
export const IS_AJAX_REQUEST = "IS_AJAX_REQUEST_FLAG";